# Generated by Django 4.1.7 on 2023-05-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.DeleteModel(
            name='StatusType',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
