# Generated by Django 4.1.7 on 2023-05-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_status_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status_type',
        ),
        migrations.AddField(
            model_name='status',
            name='division',
            field=models.CharField(choices=[('DIRETORIA', 'Diretoria'), ('LIDER DE HUB', 'Lider de Hub'), ('MEMBRO', 'Membro')], default='MEMBRO', max_length=50),
        ),
    ]
