# Generated by Django 4.1.7 on 2023-05-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_status_division_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
