# Generated by Django 4.1.1 on 2022-11-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite seu nome completo', max_length=50)),
                ('identification', models.CharField(help_text='Informe seu cpf', max_length=11)),
                ('state', models.CharField(help_text='Informe seu estado', max_length=100)),
                ('city', models.CharField(help_text='Informe sua cidade', max_length=100)),
            ],
        ),
    ]
