# Generated by Django 4.1.7 on 2023-02-15 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='static/uploads/photos/hub', verbose_name='Foto')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Hub')),
                ('regiao', models.CharField(max_length=200, verbose_name='Região do Hub')),
                ('sede', models.CharField(max_length=50, verbose_name='Sede do Hub')),
                ('representante', models.CharField(max_length=50, verbose_name='Representante Manna')),
                ('instituicoes', models.CharField(max_length=50, verbose_name='Instituições Afiliadas')),
                ('participantes', models.CharField(max_length=50, verbose_name='Membros Participantes')),
                ('conexao', models.CharField(max_length=200, verbose_name='Colégios Atendidos')),
                ('quantidadeAlunos', models.IntegerField(verbose_name='Quantidade de Alunos Atendidos')),
                ('descricao', models.CharField(max_length=2000, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='static/uploads/photos/institution', verbose_name='Foto')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Instituição')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone(Sem pontuação)')),
                ('site', models.CharField(max_length=50, verbose_name='Site')),
                ('hub', models.CharField(max_length=50, verbose_name='Hub')),
                ('esfera', models.IntegerField(choices=[(1, 'Municipal'), (2, 'Estadual'), (3, 'Federal'), (4, 'Privada'), (5, 'Outro')], default=1, verbose_name='Esfera')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('quantidadeAlunos', models.IntegerField(verbose_name='Quantidade de Alunos Relacionados ao Manna')),
                ('descricao', models.CharField(max_length=2000, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='static/uploads/photos/', verbose_name='Foto')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Completo')),
                ('categoria', models.CharField(max_length=50, verbose_name='Função')),
                ('bolsa', models.CharField(max_length=100, verbose_name='Tipo de Bolsa')),
                ('instituicao', models.CharField(max_length=50, verbose_name='Instituição')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('fone', models.CharField(max_length=50, verbose_name='Celular(Sem pontuação)')),
                ('git', models.CharField(max_length=50, verbose_name='Usuário Git')),
                ('lattes', models.CharField(max_length=50, verbose_name='Lattes')),
                ('link', models.CharField(max_length=50, verbose_name='Linkedin')),
                ('insta', models.CharField(max_length=50, verbose_name='Instagram')),
                ('twt', models.CharField(max_length=50, verbose_name='Twitter')),
                ('face', models.CharField(max_length=50, verbose_name='Facebook')),
                ('youtube', models.CharField(max_length=50, verbose_name='Youtube')),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF(Sem pontuação)')),
                ('rg', models.CharField(max_length=50, verbose_name='RG(Sem pontuação)')),
                ('genero', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino'), (3, 'Outro')], default=1, verbose_name='Gênero:')),
                ('formacao', models.CharField(max_length=50, verbose_name='Formação')),
                ('dtnasc', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('projeto', models.CharField(max_length=50, verbose_name='Projeto Associado')),
                ('premio', models.CharField(max_length=50, verbose_name='Prêmio Associado')),
                ('nomeBanco', models.CharField(max_length=50, verbose_name='Nome do Banco')),
                ('numeroBanco', models.CharField(max_length=50, verbose_name='Número do Banco')),
                ('numeroAgencia', models.CharField(max_length=50, verbose_name='Número da Agência')),
                ('numeroConta', models.CharField(max_length=50, verbose_name='Número da Conta')),
                ('termoCompromisso', models.FileField(upload_to='static/uploads/termos/', verbose_name='Termo de Compromisso')),
                ('termoCiencia', models.FileField(upload_to='static/uploads/termos/', verbose_name='Termo de Ciência')),
                ('planoTrabalho', models.FileField(upload_to='static/uploads/termos/', verbose_name='Plano de Trabalho')),
                ('lgpd', models.FileField(upload_to='static/uploads/termos/', verbose_name='LGPD')),
                ('acesso', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
