# Generated by Django 4.1.7 on 2023-02-15 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.hub'),
        ),
    ]
