# Generated by Django 4.1.1 on 2022-11-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='city',
        ),
        migrations.RemoveField(
            model_name='member',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='member',
            name='state',
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
