# Generated by Django 4.1.3 on 2022-11-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='acesso',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='nomeBanco',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='numeroAgencia',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='numeroBanco',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='numeroConta',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='termoCompromisso',
            field=models.FileField(default=0, upload_to='uploads/termos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='foto',
            field=models.ImageField(upload_to='uploads/photos'),
        ),
    ]
