# Generated by Django 4.1.7 on 2023-02-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_institution_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.institution'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lgpd',
            field=models.FileField(blank=True, upload_to='static/uploads/termos/', verbose_name='LGPD'),
        ),
    ]
