# Generated by Django 4.1.7 on 2023-02-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_member_instituicao_alter_member_lgpd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.institution', verbose_name='Instituição'),
        ),
    ]
