# Generated by Django 4.1.7 on 2023-02-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_member_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='planoTrabalho',
            field=models.FileField(blank=True, upload_to='static/uploads/termos/', verbose_name='Plano de Trabalho'),
        ),
        migrations.AlterField(
            model_name='member',
            name='termoCiencia',
            field=models.FileField(blank=True, upload_to='static/uploads/termos/', verbose_name='Termo de Ciência'),
        ),
        migrations.AlterField(
            model_name='member',
            name='termoCompromisso',
            field=models.FileField(blank=True, upload_to='static/uploads/termos/', verbose_name='Termo de Compromisso'),
        ),
    ]
