# Generated by Django 4.1.3 on 2022-11-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bolsa',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='foto',
            field=models.ImageField(upload_to='static/uploads/photos'),
        ),
        migrations.AlterField(
            model_name='member',
            name='termoCompromisso',
            field=models.FileField(upload_to='static/uploads/termos'),
        ),
    ]
