# Generated by Django 4.1.3 on 2022-11-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_member_bolsa_alter_member_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bolsa',
            field=models.CharField(max_length=100, verbose_name='Tipo de Bolsa'),
        ),
        migrations.AlterField(
            model_name='member',
            name='categoria',
            field=models.CharField(max_length=50, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cpf',
            field=models.CharField(max_length=50, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dtnasc',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='member',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='member',
            name='fone',
            field=models.CharField(max_length=50, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='member',
            name='formacao',
            field=models.CharField(max_length=50, verbose_name='Formação'),
        ),
        migrations.AlterField(
            model_name='member',
            name='foto',
            field=models.ImageField(upload_to='static/uploads/photos', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='member',
            name='git',
            field=models.CharField(max_length=50, verbose_name='Usuário Git'),
        ),
        migrations.AlterField(
            model_name='member',
            name='instituicao',
            field=models.CharField(max_length=50, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nomeBanco',
            field=models.CharField(max_length=50, verbose_name='Nome do Banco'),
        ),
        migrations.AlterField(
            model_name='member',
            name='numeroAgencia',
            field=models.CharField(max_length=50, verbose_name='Número da Agência'),
        ),
        migrations.AlterField(
            model_name='member',
            name='numeroBanco',
            field=models.CharField(max_length=50, verbose_name='Número do Banco'),
        ),
        migrations.AlterField(
            model_name='member',
            name='numeroConta',
            field=models.CharField(max_length=50, verbose_name='Número da Conta'),
        ),
        migrations.AlterField(
            model_name='member',
            name='premio',
            field=models.CharField(max_length=50, verbose_name='Prêmio Associado'),
        ),
        migrations.AlterField(
            model_name='member',
            name='projeto',
            field=models.CharField(max_length=50, verbose_name='Projeto Associado'),
        ),
        migrations.AlterField(
            model_name='member',
            name='rg',
            field=models.CharField(max_length=50, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sexo',
            field=models.CharField(max_length=50, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='termoCompromisso',
            field=models.FileField(upload_to='static/uploads/termos', verbose_name='Termo de Compromisso'),
        ),
    ]
