# Generated by Django 4.1.3 on 2022-11-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_member_bolsa_alter_member_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dtnasc',
            field=models.CharField(max_length=50, verbose_name='Data de Nascimento'),
        ),
    ]
