# Generated by Django 4.1.4 on 2022-12-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_member_dtnasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dtnasc',
            field=models.CharField(max_length=50, verbose_name='Data de Nascimento'),
        ),
    ]
