# Generated by Django 4.1.7 on 2023-02-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='sphere',
            field=models.CharField(choices=[('Municipal', 'Municipal'), ('Estadual', 'Estadual'), ('Federal', 'Federal'), ('Privada', 'Privada'), ('Outro', 'Outro')], default='Municipal', max_length=50, verbose_name='Esfera'),
        ),
    ]
