# Generated by Django 4.1.7 on 2023-02-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_institution_sphere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='commitment',
            field=models.FileField(blank=True, upload_to='./static/uploads/terms/commitment', verbose_name='Termo de Compromisso'),
        ),
        migrations.AlterField(
            model_name='member',
            name='jobPlan',
            field=models.FileField(blank=True, upload_to='./static/uploads/terms/job', verbose_name='Plano de Trabalho'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lgpd',
            field=models.FileField(blank=True, upload_to='./static/uploads/terms/lgpd', verbose_name='LGPD'),
        ),
        migrations.AlterField(
            model_name='member',
            name='science',
            field=models.FileField(blank=True, upload_to='./static/uploads/terms/science', verbose_name='Termo de Ciência'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='./static/uploads/photos/institution', verbose_name='Foto')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Projeto')),
                ('ptype', models.CharField(max_length=100, verbose_name='Tipo do Projeto')),
                ('financier', models.CharField(max_length=200, verbose_name='Financiador')),
                ('description', models.CharField(max_length=2000, verbose_name='Descrição')),
                ('relatory', models.FileField(blank=True, upload_to='./static/uploads/relatory/project', verbose_name='Relatório')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.institution', verbose_name='Instituição')),
            ],
        ),
    ]
