# Generated by Django 4.1.7 on 2023-02-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_member_commitment_alter_member_jobplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(upload_to='./static/uploads/photos/member', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(upload_to='./static/uploads/photos/project', verbose_name='Foto'),
        ),
    ]
