# Generated by Django 4.1.7 on 2023-02-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_member_photo_alter_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.project', verbose_name='Projeto'),
        ),
    ]
