# Generated by Django 4.1.4 on 2022-12-09 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_member_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF(Sem pontuação)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='fone',
            field=models.IntegerField(verbose_name='Celular(Sem pontuação)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='numeroAgencia',
            field=models.IntegerField(verbose_name='Número da Agência'),
        ),
        migrations.AlterField(
            model_name='member',
            name='numeroBanco',
            field=models.IntegerField(verbose_name='Número do Banco'),
        ),
        migrations.AlterField(
            model_name='member',
            name='numeroConta',
            field=models.IntegerField(verbose_name='Número da Conta'),
        ),
        migrations.AlterField(
            model_name='member',
            name='rg',
            field=models.CharField(max_length=50, verbose_name='RG(Sem pontuação)'),
        ),
    ]
