# Generated by Django 4.1.4 on 2022-12-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_member_ativo_alter_member_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='planoTrabalho',
            field=models.FileField(default=0, upload_to='static/uploads/termos/', verbose_name='Plano de Trabalho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='termoCiencia',
            field=models.FileField(default=0, upload_to='static/uploads/termos/', verbose_name='Termo de Ciência'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='fone',
            field=models.CharField(max_length=50, verbose_name='Celular(Sem pontuação)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='numeroAgencia',
            field=models.CharField(max_length=50, verbose_name='Número da Agência'),
        ),
        migrations.AlterField(
            model_name='member',
            name='numeroBanco',
            field=models.CharField(max_length=50, verbose_name='Número do Banco'),
        ),
        migrations.AlterField(
            model_name='member',
            name='numeroConta',
            field=models.CharField(max_length=50, verbose_name='Número da Conta'),
        ),
    ]
