# Generated by Django 4.1.4 on 2023-01-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_member_planotrabalho_member_termociencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='face',
            field=models.CharField(default=0, max_length=50, verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='insta',
            field=models.CharField(default=0, max_length=50, verbose_name='Instagram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='link',
            field=models.CharField(default=0, max_length=50, verbose_name='Linkedin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='twt',
            field=models.CharField(default=0, max_length=50, verbose_name='Twitter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='youtube',
            field=models.CharField(default=0, max_length=50, verbose_name='Youtube'),
            preserve_default=False,
        ),
    ]
