# Generated by Django 4.1.4 on 2023-01-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_member_lattes'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lgpd',
            field=models.FileField(default=0, upload_to='static/uploads/termos/', verbose_name='LGPD'),
            preserve_default=False,
        ),
    ]
