# Generated by Django 4.1.4 on 2023-01-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_member_lgpd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='static/uploads/photos/institution', verbose_name='Foto')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Instituição')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone(Sem pontuação)')),
                ('site', models.CharField(max_length=50, verbose_name='Site')),
                ('hub', models.CharField(max_length=50, verbose_name='Hub do Manna')),
                ('esfera', models.IntegerField(choices=[(1, 'Municipal'), (2, 'Estadual'), (3, 'Federal'), (4, 'Privada'), (5, 'Outro')], default=1, verbose_name='Esfera')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('quantidadeAlunos', models.IntegerField(verbose_name='Quantidade de Alunos Relacionados ao Manna')),
                ('descricao', models.CharField(max_length=2000, verbose_name='Descrição')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='dtnasc',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='member',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
    ]
