# Generated by Django 4.1.7 on 2023-02-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_rename_name_scholarship_stype_scholarship_financier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bag',
        ),
        migrations.AddField(
            model_name='member',
            name='scholarship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pages.scholarship', verbose_name='Bolsa'),
            preserve_default=False,
        ),
    ]
