# Generated by Django 4.1.4 on 2023-01-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_institution_alter_member_dtnasc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='static/uploads/photos/hub', verbose_name='Foto')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Instituição')),
                ('sede', models.CharField(max_length=50, verbose_name='Sede do Hub')),
                ('representante', models.CharField(max_length=50, verbose_name='Representante Manna')),
                ('instituicoes', models.CharField(max_length=50, verbose_name='Instituições Membro')),
                ('participantes', models.CharField(max_length=50, verbose_name='Membros Participantes')),
                ('conexao', models.CharField(max_length=200, verbose_name='Colégios Atendidos')),
                ('quantidadeAlunos', models.IntegerField(verbose_name='Quantidade de Alunos Atendidos')),
                ('descricao', models.CharField(max_length=2000, verbose_name='Descrição')),
            ],
        ),
    ]
