# Generated by Django 4.1.4 on 2023-01-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='instituicoes',
            field=models.CharField(max_length=50, verbose_name='Instituições Afiliadas'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Hub'),
        ),
    ]
