# Generated by Django 4.1.7 on 2023-02-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_scholarship_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='Member',
            new_name='member',
        ),
    ]
