# Generated by Django 4.1.4 on 2023-01-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_hub_instituicoes_alter_hub_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='região',
            field=models.CharField(default=0, max_length=200, verbose_name='Região do Hub'),
            preserve_default=False,
        ),
    ]
