# Generated by Django 4.1.4 on 2023-01-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_hub_região'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hub',
            old_name='região',
            new_name='regiao',
        ),
    ]
