# Generated by Django 4.1.7 on 2023-03-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_rename_member_scholarship_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('event', models.CharField(max_length=200, verbose_name='Evento')),
                ('link', models.CharField(max_length=200, verbose_name='Link do Evento')),
                ('description', models.CharField(max_length=2000, verbose_name='Descrição')),
                ('pdf', models.FileField(blank=True, upload_to='./static/uploads/publication', verbose_name='PDF')),
                ('member', models.ManyToManyField(to='pages.member', verbose_name='Membro')),
            ],
        ),
    ]
