# Generated by Django 4.1.7 on 2023-03-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='link',
            new_name='linkEvent',
        ),
        migrations.AddField(
            model_name='publication',
            name='publicationType',
            field=models.CharField(default=1, max_length=200, verbose_name='Tipo de Publicação'),
            preserve_default=False,
        ),
    ]
