# Generated by Django 4.1.7 on 2023-03-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_rename_link_publication_linkevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('eventType', models.CharField(max_length=200, verbose_name='Tipo de Evento')),
                ('dateStart', models.DateField(verbose_name='Data de Início do Evento')),
                ('dateEnd', models.DateField(verbose_name='Data de Finalização do Evento')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('description', models.CharField(max_length=2000, verbose_name='Descrição')),
                ('photo', models.ImageField(blank=True, upload_to='./static/uploads/photos/event', verbose_name='Foto')),
                ('organization', models.ManyToManyField(to='pages.member', verbose_name='Organização')),
            ],
        ),
    ]
