# Generated by Django 4.1.7 on 2023-03-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
    ]
