# Generated by Django 4.1.7 on 2023-03-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_event_address_alter_event_dateend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateEnd',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Finalização do Evento'),
        ),
        migrations.AlterField(
            model_name='project',
            name='relatory',
            field=models.FileField(blank=True, null=True, upload_to='./static/uploads/relatory/project', verbose_name='Relatório'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf',
            field=models.FileField(upload_to='./static/uploads/publication', verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='relatory',
            field=models.FileField(blank=True, null=True, upload_to='./static/uploads/relatory/scholarship', verbose_name='Relatório'),
        ),
    ]
