# Generated by Django 4.1.7 on 2023-04-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_awards_delete_award_alter_member_award_awards_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Awards',
        ),
    ]
