# Generated by Django 4.1.7 on 2023-04-10 18:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_remove_member_award_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='Masculino', max_length=50, verbose_name='Gênero:')),
                ('birthday', models.DateField(verbose_name='Data de Nascimento')),
                ('school', models.CharField(max_length=200, verbose_name='Escola')),
                ('mannaNumber', models.IntegerField(verbose_name='Número do Manna')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.event', verbose_name='Evento')),
                ('hub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.hub')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.project', verbose_name='Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF(Sem pontuação)')),
                ('hours', models.IntegerField(verbose_name='Carga Horária')),
                ('description', models.CharField(max_length=2000, verbose_name='Descrição')),
                ('code', models.CharField(max_length=200, verbose_name='Código')),
                ('pdf', models.FileField(upload_to='./static/uploads/certificate', verbose_name='Certificado')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.event', verbose_name='Evento')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.project', verbose_name='Projeto')),
            ],
        ),
    ]
