# Generated by Django 4.1.7 on 2023-04-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_students_certificate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
