# Generated by Django 4.1.7 on 2023-04-10 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_rename_students_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.project', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='student',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.hub'),
        ),
        migrations.AlterField(
            model_name='student',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.project', verbose_name='Projeto'),
        ),
    ]
