# Generated by Django 4.1.7 on 2023-05-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_alter_certificate_event_alter_certificate_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='acess',
        ),
        migrations.RemoveField(
            model_name='member',
            name='activity',
        ),
    ]
